name: nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - pillow
  - nltk
  - sympy
  - networkx
  - joblib
  - packaging
  - python-dateutil
  - requests
  - tqdm
  - pyyaml
  - typing-extensions
  - regex
  - smart-open
  - gensim
  - sentence-transformers
  - transformers
  - tokenizers
  - jinja2
  - xgboost
  - tensorflow
  - keras
  - pip:
      - torch==2.2.2+cpu
      - torchvision==0.20.1+cpu
      - torchaudio==2.2.2+cpu
